from models.simplenet_MobileConv import SimpleNet_Mobile
from models.simplenet_FALCON import SimpleNetOutputEHP
from models.simplenet_standardConv import SimpleNetOriginal
from models.simplenet_FALCON_rank import RankFALCONSimpleNet